// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDgBHCYHZPphdaEA7WSwm9vUWSlrHm3Ow',
    appId: '1:1068575332396:android:da2b37dbb624047a271989',
    messagingSenderId: '1068575332396',
    projectId: 'society-management-syste-771be',
    storageBucket: 'society-management-syste-771be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7PqSsAEsKEPlei8yjAOnVWuDvlSk983o',
    appId: '1:1068575332396:ios:0e6a3c3dd90e3d0e271989',
    messagingSenderId: '1068575332396',
    projectId: 'society-management-syste-771be',
    storageBucket: 'society-management-syste-771be.appspot.com',
    iosBundleId: 'com.example.society',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7PqSsAEsKEPlei8yjAOnVWuDvlSk983o',
    appId: '1:1068575332396:ios:690408f1f2176b66271989',
    messagingSenderId: '1068575332396',
    projectId: 'society-management-syste-771be',
    storageBucket: 'society-management-syste-771be.appspot.com',
    iosBundleId: 'com.example.society.RunnerTests',
  );
}
